# To RUN
# docker-compose up -d

# Checking running containers
# docker-compose ps

# Stopping
# docker-compose stop

mysql:
  image: mysql:5.6.34
  environment:
   - MYSQL_ROOT_PASSWORD=pass
   - MYSQL_DATABASE=tasklogs
  ports:
    - "3306:3306"
rabbitmq:
  image: rabbitmq:3-management
  ports:
    - "5671:5671"
    - "5672:5672"
    - "15672:15672"